config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create] do
    collection do
      get :edit
      get :update
    end
  end

  resources :sessions, only: [:new, :create, :destroy] do
    delete :destroy, on: :collection
  end


  resources :ideas do
    resources :comments
    resources :likes, only: [:create, :destroy]
  end

  root 'ideas#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

  can :manage, [Idea, Comment] do |x|
    x.user == user
  end

  can :destroy, [Like] do |x|
    x.user == user
  end
end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :idea
  belongs_to :user

  validates :body, presence: {message: "Comment is required"},
                   uniqueness: {scope: :idea_id}

  def user_name
    if user
      user.first_name
    else
      "Anonymous"
    end
  end

end

app/models/idea.rb
class Idea < ActiveRecord::Base

  belongs_to :user
  has_many :comments, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :users, through: :likes

  validates :title, presence: {message: "Must have a title"}

  def like_for(user)
    likes.find_by_user_id(user.id)
  end

  def user_name
   if user
     user.first_name
   else
     "Anonymous"
   end
 end
end

app/models/like.rb
class Like < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :idea

  validates :idea_id, uniqueness: {scope: :user_id}
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :ideas, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :liked_ideas, through: :likes, source: :idea

  validates :email, presence: true, uniqueness: true,
          format: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i


def liked_idea?(idea)
  liked_ideas.include?(idea)
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate_user!
    redirect_to new_session_path unless user_signed_in?
  end

  def user_signed_in?
    current_user.present?
  end
  helper_method :user_signed_in?

  def current_user
    @current_user ||= User.find_by_id session[:user_id]
  end
  helper_method :current_user
  end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment      = Comment.new comment_params
    @idea         = Idea.find params[:idea_id]
    @comment.user = current_user
    @comment.idea = @idea
    if @comment.save
      redirect_to idea_path(@idea), notice: "Comment Added"
    else
      flash[:alert] = "Comment not added"
      render '/ideas/show'
    end
  end


  private

  def comment_params
    params.require(:comment).permit([:body])
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :find_idea, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  def new
    @idea = Idea.new
  end

  def create
    @idea       = Idea.new(idea_params)
    @idea.user  = current_user
    if @idea.save
      redirect_to idea_path(@idea), notice: "Idea Posted!"
    else
      flash[:alert] = "Errors while Posting"
      render :new
    end
  end

  def index
    @ideas = Idea.all
  end

  def show
    @comment = Comment.new
  end

  def edit
  end

  def update
    if @idea.update idea_params
      redirect_to idea_post(@idea), notice: "Idea Edited"
    else
      flash[:alert] = "Idea not Updated"
    end
  end

  def destroy
    @idea.destroy
    redirect_to ideas_path
  end


  private

  def idea_params
    params.require(:idea).permit([:title, :body])
  end

  def find_idea
    @idea = Idea.find params[:id]
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @idea     = Idea.find params[:idea_id]
    @like     = Like.new(idea: @idea, user: current_user)
      if @like.save
        redirect_to @idea, notice: "Liked"
      else
        redirect_to @idea, alert: "Sorry, Can't like"
      end
    end

  def destroy
    @like     = Like.find params[:id]
    @idea     = Idea.find params[:idea_id]
    if can? :destroy, @like
      @like.destroy
      redirect_to idea_path(@idea), notice: "Unliked"
    else
      redirect_to new_session_path, alert: "Please Sign In"
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_email params[:email]
      if @user && @user.authenticate(params[:password])
        session[:user_id] = @user.id
        redirect_to ideas_path, notice: "Signed in successfully"
      else
        flash[:alert] = "Wrong Credentials"
        render :new
      end
    end

    def destroy
      session[:user_id] = nil
      redirect_to ideas_path, notice: "Logged Out!"
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
      @user = User.new
    end

    def create
      @user = User.new user_params
      if @user.save
        session[:user_id] = @user.id
        redirect_to root_path, notice: "Logged in"
      else
        flash[:alert] = "Read Error"
        render :new
      end
    end

    def update
    end

    private

    def user_params
      params.require(:user).permit([:first_name, :last_name, :email, :password, :password_confirmation])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ideas/_form.html.erb
<div class="container">
  <%= form_for @idea do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.submit class:"btn btn-primary btn-xs"  %>
    <% end %>
  </div>
</div>

app/views/ideas/edit.html.erb
<div class="container header">
  <h2>Edit Idea</h2>

    <%= render "form" %>

</div>

app/views/ideas/index.html.erb
<div class="container">
  <article>
<h2>Welcome to My Ideas Page</h2>
  <% @ideas.each do |idea| %>
    <article>
      <p>
        <b><h4><%= link_to idea.title, idea %></h4></b>
        <%= idea.body %><br><br>
        <b>By:</b> <%= link_to idea.user.first_name, idea %>
        <b>Created At: </b><%= idea.created_at %>
            <% end %>
      </article>
  </article>
</div>


</div>

app/views/ideas/new.html.erb
<div class="container">
  <h2>Post New Idea</h2>

<%= render "form" %>

</div>

app/views/ideas/show.html.erb
<div class="container">
  <article>
  <h2><%= @idea.title %></h2>
      <p><%= @idea.body %></p>
  <p><b>Created On:</b> <%= @idea.created_at %> <b>By: </b> <%= @idea.user_name %> 
  </p>

 <div class="container button-group">
  <%= link_to "Back", ideas_path, class:"btn btn-primary btn-xs"%>
  <%= link_to "Edit", edit_idea_path, class: "btn btn-warning btn-xs"%>
  <%= link_to "Delete", idea_path(@idea), class: "btn btn-danger btn-xs", method: :delete, data: {confirm: "Are you sure?"}%>
  </div>

  <div class="container right">
    <% if user_signed_in? %>
      <% if current_user.liked_idea?(@idea) %>
      <%= link_to "Un-Like", idea_like_path(@idea, @idea.like_for(current_user)), class: "btn btn-primary btn-xs", method: :delete, title: "Un-Like" %>
      <% elsif %>
      <%= link_to "Like", idea_likes_path(@idea), class: "btn btn-danger btn-xs", method: :post%>
      <% end %>
      <% end %>
      <%= @idea.likes.count %>
  </div>

  </article>
</div>

<div class="container comments">
   <h5>Add New Comments</h5>
    <%= form_for [@idea, @comment] do |f| %>
   <div class="form-group">
     <%= f.text_area :body, class: "form-control"%>
   </div>
   <div class="form-group">
     <%= f.submit class:"btn btn-primary btn-xs"  %>
     <% end %>
   </div>
 </div>

 <div class="container comments">
   <h5>Comments</h5>
     <% @idea.comments.each do |com| %>
     <div class="well">
       <p><%= com.body %></p>
       <p><b>Created:</b> <%= com.created_at %><b>By: </b><%= com.user_name %></p>
     </div>
   <% end %>
 </div>

 </div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">

  <div class="container">

    <div class="navbar-header">
      <%= link_to "My </> Idea", ideas_path, class: "navbar-brand" %>
    </div>

    <div class="navbar-body">
      <ul class="nav navbar-nav">
        <li><%= link_to "My Ideas", ideas_path %></li>
        <li><%= link_to "Create Idea", new_idea_path %></li>
      </ul>
    </div>

    <div class="navbar-right">


      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li class="navbar-text"> <p>Hello <%= current_user.first_name %>,
            <%= link_to "Sign-Out", sessions_path, method: :delete, data: {confirm: "are you sure you want to log out?"} %></p></li>
              <% else %>
          <li><%= link_to "Sign Up", new_user_path %></li>
          <li><%= link_to "Sign In", new_session_path %></li>
            <% end %>
      </ul>
    </div>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IdeaFactory</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/nav' %>
<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<div class="container">
  <h2>Sign Up</h2>
<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
</div>


<div class="container Sign-Up">
    <%= form_for @user do |f| %>

    <div class="form-group">
      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.submit class:"btn btn-primary btn-xs" %>
    </div>
<% end %>

</div>